<?php 

$cars = [
    [
        'id' => "1",
        'brand' => "fiat",
        'modello' => "panda",
        'anno' => "2019",
        'colore' => "arancione",
        'alimentazione' => "benzina", 
        'chilometraggio' => "90000",
        'porte' => "5",
        'cavalli' => "71",
        'caratteristicheAuto' => "È agile e ha uno sterzo preciso, ma le sospensioni morbide la rendono inadatta alla guida sportiva; fluido e poco assetato il 1.2 a benzina, migliorabile il cambio. Il prezzo appare attraente, ma si devono mettere in conto gli accessori, e la Easy fa pagare a parte pure il climatizzatore.", 
        'nProprietari' => "1",
        'condizioni' => "ottime",
        'foto' => "//immagini.alvolante.it/sites/default/files/styles/anteprima_lunghezza_640_jpg/public/serie_auto_galleria/2011/12/fiat_panda_ant_0.png?itok=1MgNMqsq",
        'prezzo' => "9000"
    ],
    [
        'id' => "2",
        'brand' => "ford",
        'modello' => "ecosport",
        'anno' => "2020",
        'colore' => "rosso",
        'alimentazione' => "benzina", 
        'chilometraggio' => "60000",
        'porte' => "5",
        'cavalli' => "125",
        'caratteristicheAuto' => "Costruita nello stabilimento romeno di Craiova e rinnovata all'inizio del 2018, questa piccola crossover ha un frontale massiccio e grintoso, con una mascherina più grande e rialzata a filo del cofano.", 
        'nProprietari' => "1",
        'condizioni' => "come nuovo",
        'foto' => "//immagini.alvolante.it/sites/default/files/styles/anteprima_lunghezza_640_jpg/public/serie_auto_galleria/2013/10/ford_edge_top_ant.png?itok=k-bbF0QO",
        'prezzo' => "17500"
    ],
    [
        'id' => "3",
        'brand' => "hunday",
        'modello' => "bayon",
        'anno' => "2021",
        'colore' => "bianco",
        'alimentazione' => "benzina", 
        'chilometraggio' => "10000",
        'porte' => "5",
        'cavalli' => "84",
        'caratteristicheAuto' => "La Hyundai Bayon è una crossover compatta che nasce sulla base della utilitaria i20, addirittura condividendone la plancia e le porte anteriori.", 
        'nProprietari' => "2",
        'condizioni' => "come nuovo",
        'foto' => "//immagini.alvolante.it/sites/default/files/styles/anteprima_lunghezza_640_jpg/public/serie_auto_galleria/2021/06/hyundai_bayon_ant.png?itok=g65aRkkU",
        'prezzo' => "20500"
    ],
    [
        'id' => "4",
        'brand' => "lancia",
        'modello' => "ypsilon",
        'anno' => "2016",
        'colore' => "rosso",
        'alimentazione' => "ibrida", 
        'chilometraggio' => "31000",
        'porte' => "5",
        'cavalli' => "69",
        'caratteristicheAuto' => "La Lancia Ypsilon ha una carrozzeria originale (con spunti un po’ moderni e un po’ rétro) e offre la praticità delle cinque porte, con quelle posteriori che si notano poco per via delle (non comode) maniglie “nascoste” dietro i finestrini.", 
        'nProprietari' => "2",
        'condizioni' => "buone",
        'foto' => "//immagini.alvolante.it/sites/default/files/styles/anteprima_lunghezza_640_jpg/public/serie_auto_galleria/2011/04/lancia_ypsilon_top_ant_0.png?itok=vJpZYytq",
        'prezzo' => "7500"
    ],
    [
        'id' => "5",
        'brand' => "opel",
        'modello' => "corsa",
        'anno' => "2018",
        'colore' => "grigio",
        'alimentazione' => "gasolio", 
        'chilometraggio' => "98300",
        'porte' => "3",
        'cavalli' => "102",
        'caratteristicheAuto' => "La nuova edizione della Opel Corsa non ha nulla in comune con la precedente, la cui meccanica era in parte condivisa con la Fiat Grande Punto", 
        'nProprietari' => "2",
        'condizioni' => "buone",
        'foto' => "//immagini.alvolante.it/sites/default/files/styles/anteprima_lunghezza_640_jpg/public/serie_auto_galleria/2019/07/opel_corsa_ant.png?itok=2t8dljP5",
        'prezzo' => "8400"
    ],
    [
        'id' => "6",
        'brand' => "smart",
        'modello' => "fortwo",
        'anno' => "2020",
        'colore' => "nero",
        'alimentazione' => "elettrica", 
        'chilometraggio' => "9400",
        'porte' => "2",
        'cavalli' => "82",
        'caratteristicheAuto' => "Ora solo elettrica, la Smart fortwo è la 'regina' della città: più corta di tutti gli altri modelli di almeno 70-80 cm, in pratica può girare su se stessa.", 
        'nProprietari' => "1",
        'condizioni' => "come nuovo",
        'foto' => "//immagini.alvolante.it/sites/default/files/styles/anteprima_lunghezza_640_jpg/public/serie_auto_galleria/2014/08/smart_fortwo_coupe_ant_0.png?itok=hTs5JVJL",
        'prezzo' => "17400"
    ],
    [
        'id' => "7",
        'brand' => "volkswagen",
        'modello' => "amarok",
        'anno' => "2016",
        'colore' => "blue",
        'alimentazione' => "gasolio", 
        'chilometraggio' => "43000",
        'porte' => "5",
        'cavalli' => "204",
        'caratteristicheAuto' => "Assemblato in Argentina, il Volkswagen Amarok è un grande pick-up a doppia cabina dalle linee decise, con frontale ispirato alla suv Tiguan e larghi passaruota.", 
        'nProprietari' => "2",
        'condizioni' => "ottime",
        'foto' => "//immagini.alvolante.it/sites/default/files/styles/anteprima_lunghezza_640_jpg/public/serie_auto_galleria/2010/12/vw_amarok_highline_ant.png?itok=_dCUU2Vw",
        'prezzo' => "25000"
    ],
    [
        'id' => "8",
        'brand' => "skoda",
        'modello' => "fabia",
        'anno' => "2017",
        'colore' => "arancione",
        'alimentazione' => "benzina", 
        'chilometraggio' => "146000",
        'porte' => "5",
        'cavalli' => "95",
        'caratteristicheAuto' => "Fra le utilitarie, la Skoda Fabia si distingue per gli interni davvero spaziosi. Complice la lunghezza della carrozzeria di 411 cm, un valore piuttosto alto per questo genere di vetture", 
        'nProprietari' => "2",
        'condizioni' => "buone",
        'foto' => "//immagini.alvolante.it/sites/default/files/styles/anteprima_lunghezza_640_jpg/public/serie_auto_galleria/2021/07/skoda_fabia_top_ant.png?itok=ZH1jwgdj",
        'prezzo' => "9500"
    ],
    [
        'id' => "8",
        'brand' => "subaru",
        'modello' => "forester",
        'anno' => "2019",
        'colore' => "bianco",
        'alimentazione' => "benzina", 
        'chilometraggio' => "5000",
        'porte' => "5",
        'cavalli' => "150",
        'caratteristicheAuto' => "Si tratta di una suv 4x4 dalle forme possenti e spigolose, che pone l'accento sulla comodità e sulla capacità di muoversi quasi ovunque, anche sui fondi molto viscidi e sconnessi. ", 
        'nProprietari' => "1",
        'condizioni' => "buone",
        'foto' => "//immagini.alvolante.it/sites/default/files/styles/anteprima_lunghezza_640_jpg/public/serie_auto_galleria/2021/12/subaru_forester_ant.png?itok=T_Iu3qZD",
        'prezzo' => "32000"
    ],
    [
        'id' => "9",
        'brand' => "toyota",
        'modello' => "corolla",
        'anno' => "2020",
        'colore' => "blue",
        'alimentazione' => "benzina", 
        'chilometraggio' => "24000",
        'porte' => "5",
        'cavalli' => "98",
        'caratteristicheAuto' => "Tornata allo storico nome Corolla (quello della macchina più venduta al mondo, da quel 1966 in cui venne lanciata la prima edizione) l’erede della Auris ha una linea filante", 
        'nProprietari' => "1",
        'condizioni' => "ottime",
        'foto' => "//immagini.alvolante.it/sites/default/files/styles/anteprima_lunghezza_640_jpg/public/serie_auto_galleria/2019/02/toyota_corolla_ant_1.png?itok=O5_ubUmN",
        'prezzo' => "22500"
    ],
    [
        'id' => "10",
        'brand' => "volvo",
        'modello' => "s90",
        'anno' => "2018",
        'colore' => "grigio",
        'alimentazione' => "benzina", 
        'chilometraggio' => "19700",
        'porte' => "5",
        'cavalli' => "211",
        'caratteristicheAuto' => "La Volvo S90 è la più grande fra le berline della casa svedese; sviluppata sulla stessa piattaforma delle suv XC90 e XC60, è filante e sobria.", 
        'nProprietari' => "1",
        'condizioni' => "ottime",
        'foto' => "//immagini.alvolante.it/sites/default/files/styles/anteprima_lunghezza_640_jpg/public/serie_auto_galleria/2016/05/volvo_s90_ant.png?itok=_CiSqNx6",
        'prezzo' => "50000"
    ],
    [
        'id' => "11",
        'brand' => "alfa romeo",
        'modello' => "stelvio",
        'anno' => "2021",
        'colore' => "rosso",
        'alimentazione' => "gasolio", 
        'chilometraggio' => "11500",
        'porte' => "5",
        'cavalli' => "160",
        'caratteristicheAuto' => "L'Alfa Romeo Stelvio è la prima suv della casa del Biscione. Sotto le linee grintose ma 'pulite', caratterizzate da un'eleganza tutta italiana", 
        'nProprietari' => "1",
        'condizioni' => "pari al nuovo",
        'foto' => "//immagini.alvolante.it/sites/default/files/styles/anteprima_lunghezza_640_jpg/public/serie_auto_galleria/2017/01/alfa_romeo_stelvio_ant_1.png?itok=Gn9p9Efb",
        'prezzo' => "50900"
    ],
    [
        'id' => "12",
        'brand' => "audi",
        'modello' => "a6",
        'anno' => "2018",
        'colore' => "grigio",
        'alimentazione' => "ibrida", 
        'chilometraggio' => "108000",
        'porte' => "5",
        'cavalli' => "299",
        'caratteristicheAuto' => "Questa grande (494 cm da un paraurti all’altro) e ben rifinita berlina è comoda e piacevole da guidare. ", 
        'nProprietari' => "2",
        'condizioni' => "buone",
        'foto' => "//immagini.alvolante.it/sites/default/files/styles/anteprima_lunghezza_640_jpg/public/serie_auto_galleria/2018/05/audi_a6_ant.png?itok=wLHTenvv",
        'prezzo' => "32000"
    ],
    [
        'id' => "13",
        'brand' => "bmw",
        'modello' => "x1",
        'anno' => "2017",
        'colore' => "bianco",
        'alimentazione' => "gasolio", 
        'chilometraggio' => "97000",
        'porte' => "5",
        'cavalli' => "116",
        'caratteristicheAuto' => "La BMW X1 è la più piccola tra le suv della casa tedesca; in questa seconda generazione", 
        'nProprietari' => "2",
        'condizioni' => "ottime",
        'foto' => "//immagini.alvolante.it/sites/default/files/styles/anteprima_lunghezza_640_jpg/public/serie_auto_galleria/2015/08/bmw_x1m_ant.png?itok=kiDoHeP_",
        'prezzo' => "30900"
    ],
    [
        'id' => "14",
        'brand' => "dacia",
        'modello' => "duster",
        'anno' => "2019",
        'colore' => "nero",
        'alimentazione' => "benzina", 
        'chilometraggio' => "21200",
        'porte' => "5",
        'cavalli' => "91",
        'caratteristicheAuto' => "Come tutte le Dacia, anche la suv Duster punta sul favorevole rapporto dotazione/prezzo.", 
        'nProprietari' => "2",
        'condizioni' => "ottime",
        'foto' => "//immagini.alvolante.it/sites/default/files/styles/anteprima_lunghezza_640_jpg/public/serie_auto_galleria/2018/01/dacia_duster_top_ant_0.png?itok=NMLOX61m",
        'prezzo' => "18500"
    ],
    [
        'id' => "15",
        'brand' => "dacia",
        'modello' => "spring",
        'anno' => "2021",
        'colore' => "bianco",
        'alimentazione' => "elettrica", 
        'chilometraggio' => "5000",
        'porte' => "5",
        'cavalli' => "45",
        'caratteristicheAuto' => "La Dacia Spring è una citycar elettrica low-cost in stile crossover. Davanti sono in evidenza il grande paraurti e i fari a led affilati, mentre la mascherina cela lo sportellino di ricarica", 
        'nProprietari' => "1",
        'condizioni' => "ottime",
        'foto' => "//immagini.alvolante.it/sites/default/files/styles/anteprima_lunghezza_640_jpg/public/serie_auto_galleria/2021/06/dacia_spring_ant.png?itok=q21tnztQ",
        'prezzo' => "15000"
    ],
]

?>